name: unit-tests
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
jobs:
  unit-tests:
    name: unit-tests
    permissions: write-all
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-unit-tests
      cancel-in-progress: true
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Fund Nexus
        run: bun run fund:nexus 84532 10
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PRIVATE_KEY_TWO: ${{ secrets.PRIVATE_KEY_TWO }}
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
          TESTNET_CHAIN_ID: 84532
          MAINNET_CHAIN_ID: 10

      - name: Run the tests
        run: bun run test --bail=1
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PRIVATE_KEY_TWO: ${{ secrets.PRIVATE_KEY_TWO }}
          PIMLICO_API_KEY: ${{ secrets.PIMLICO_API_KEY }}
          PAYMASTER_URL: ${{ secrets.PAYMASTER_URL }}
          BUNDLER_URL: ${{ secrets.BUNDLER_URL }}
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
          TESTNET_CHAIN_ID: 84532
          MAINNET_CHAIN_ID: 10
          RUN_PAID_TESTS: false
          CI: true 
